apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment and configure storageClassName if you have a specific storage class
  # storageClassName: standard
